### ISSUE TITLE
Transfer project

### ISSUE THREAD

**Issue by stevenvachon** [stevenvachon/broquire#3]
If you aren't going to support this project anymore, please transfer it over to me as I have a use for it and this is a good name for the functionality.

**Comment by mikeal** [comment]
Tried to transfer it but it says that "stevenvachon/broquire already exists."

**Comment by stevenvachon** [comment]
Hi! I've just renamed my fork, so it should be safe to reattempt.

**Comment by mikeal** [comment]
Now it says "stevenvachon already has a repository in the mikeal/broquire network
 Unwatch " :)

**Comment by stevenvachon** [comment]
Ok, repo deleted. Next it'll want me to remove my account, haha

**Comment by mikeal** [comment]
"Repository transfer to stevenvachon requested"

**Comment by stevenvachon** [comment]
@mikeal Done! Please transfer the npm package as well; same username.

**Comment by mikeal** [comment]
```
% npm owner add stevenvachon broquire        
+ stevenvachon (broquire)
```

**Comment by stevenvachon** [comment]
Should I remove you from it in the future or do you want to keep your name on it? I don't mind.

**Comment by stevenvachon** [comment]
I'll take that as a no :)

Thanks for transferring!

**Comment by mikeal** [comment]
I have no preference :)

**Comment by stevenvachon** [comment]
I'll leave it in. My work here is derivative. v1.0 released, by the way.
